In [4]:
import numpy as np

In [5]:
list1 = [1,2,3,4,5,6]

In [6]:
arr = np.array(list1)

In [7]:
type(arr)

numpy.ndarray

In [12]:
arr1 = np.arange(0,100,10)

In [13]:
print(arr1)

[ 0 10 20 30 40 50 60 70 80 90]


In [14]:
arr2 = np.arange(10)

In [15]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr3 = np.arange(10,100) 

In [17]:
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [18]:
rand1 = np.random.randint(1,100) 

In [19]:
rand1

70

In [21]:
rand2 = np.random.randint(1,100,10)

In [22]:
rand2

array([80, 53, 25,  9, 84, 96, 21, 35, 57, 56])

In [27]:
rand2.max()

96

In [28]:
rand2.argmax() #INDEX OF MAX VALUE

5

In [24]:
rand2.min()

9

In [29]:
rand2.argmin()

3

In [30]:
rand2.mean()

51.6

In [31]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
arr2d = np.random.randint(0,1000,100).reshape((10,10))

In [36]:
arr2d

array([[371, 284, 677, 901, 953, 207, 650,  41, 894, 295],
       [776, 266,  28,  36,  83, 603, 109,  94, 428, 102],
       [352, 990,  13, 881, 210, 905,  12, 252, 921, 628],
       [256, 908, 328, 835, 344, 109, 386, 178, 584, 126],
       [ 96,  41, 874, 280, 872, 182, 653, 391,   0, 862],
       [199, 607, 769, 484,  10, 222, 942,  99,  92, 959],
       [627, 900, 747, 352, 753, 753, 654, 860, 469, 501],
       [535, 338, 228, 591, 368, 650, 586,  29, 353,  23],
       [584, 612, 475, 868, 882, 571,  89, 125, 447, 590],
       [443, 940, 525, 198, 693, 404, 131, 598,  72, 437]])

In [37]:
arr2d[0,1]

284

In [38]:
arr2d[0:5,0:5]

array([[371, 284, 677, 901, 953],
       [776, 266,  28,  36,  83],
       [352, 990,  13, 881, 210],
       [256, 908, 328, 835, 344],
       [ 96,  41, 874, 280, 872]])